name: test65
favicon: null
layout_spectrum: 1
typography_spectrum: 0.27281
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#34373f'
    - '#f30018'
    - '#979797'
    - '#009acc'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
